spring.application.name=cine_back
server.port=8080
spring.datasource.url=\jdbc:postgresql://aws-0-us-west-1.pooler.supabase.com:6543/postgres?user=postgres.avfdvbiubjfreszcpwhw&password=Bloodbornejajc
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
alect.MySQL8Dialect
spring.rabbitmq.host=217.77.12.236
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.jackson.serialization.fail-on-empty-beans=false
